In [2]:
# Importing Libraries
import pandas as pd
import numpy as np
import os

In [4]:
# Import data and turn project path into a string
path = r'/Users/jerrysiphavong/Desktop/12-2024 Instacart Basket Analysis'

In [6]:
# Importing orders_products_merged_updated
df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data' , 'Prepared Data' , 'orders_products_merged_updated.pkl'))

In [12]:
# Create subset
df = df_ords_prods_merge[:1000000]

In [14]:
df.shape

(1000000, 18)

In [16]:
df.groupby('product_name')

# Aggregating Data with agg()

In [19]:
# Use groupby() function
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.562844
2                17.518895
3                16.907152
4                17.537934
5                14.894521
6                16.658449
7                17.072954
8                14.942021
9                15.447580
10               18.681852
11               15.352278
12               14.327957
13               16.578690
14               16.666369
15               16.153766
16               17.768070
17               15.602964
18               19.674252
19               16.924344
20               16.292631
21               25.535596

In [21]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.562844   1  99
2                17.518895   1  96
3                16.907152   1  99
4                17.537934   1  99
5                14.894521   1  99
6                16.658449   1  99
7                17.072954   1  99
8                14.942021   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.352278   1  99
12               14.327957   1  99
13               16.578690   1  99
14               16.666369   1  99
15               16.153766   1  99
16               17.768070   1  99
17               15.602964   1  99
18               19.674252   1  99
19               16.924344   1  99
20               16.292631   1  99
21               25.535596   1  98

# Aggregating Data with transform()

In [28]:
df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [32]:
# Print head of dataframe with an argument of 100
df_ords_prods_merge.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,NaN,10,0,both,Mid-range product,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Slowest days,Average orders,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,prior,8,3,11,23.0,5,0,both,Mid-range product,Slowest days,Most orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,prior,18,1,14,30.0,1,0,both,Mid-range product,Busiest days,Most orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,prior,13,5,16,2.0,8,0,both,Mid-range product,Regularly busy,Most orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,prior,16,3,13,0.0,2,0,both,Mid-range product,Slowest days,Most orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,prior,10,2,15,3.0,6,0,both,Mid-range product,Regularly busy,Most orders,21

In [38]:
# For all 
pd.options.display.max_rows = None

In [42]:
df_ords_prods_merge.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,NaN,10,0,both,Mid-range product,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Slowest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,7,26.0,7,0,both,Mid-range product,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,10,30.0,1,0,both,Mid-range product,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,20,19.0,1,0,both,Mid-range product,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,12,15.0,2,1,both,Mid-range product,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,prior,1,5,11,NaN,1,0,both,Mid-range product,Regularly busy,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,13,7.0,1,0,both,Mid-range product,Slowest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,13,7.0,3,1,both,Mid-range product,Slowest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,12,12.0,4,1,both,Mid-range product,Regularly busy,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,10,2.0,8,0,both,Mid-range product,Slowest days,Most orders,13
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,prior,7,2,8,6.0,18,1,both,Mid-range product,Regularly busy,Average orders,13
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,prior,9,5,8,10.0,12,1,both,Mid-range product,Regularly busy,Average orders,13
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,prior,4,2,0,7.0,10,0,both,Mid-range product,Regularly busy,Fewest orders,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,prior,5,1,21,6.0,9,1,both,Mid-range product,Busiest days,Average orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,prior,6,1,0,14.0,9,1,both,Mid-range product,Busiest days,Fewest orders,28
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,prior,7,2,2,8.0,7,1,both,Mid-range product,Regularly busy,Fewest orders,28
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,prior,8,1,23,6.0,6,1,both,Mid-range product,Busiest days,Fewest orders,28
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,prior,9,1,3,28.0,6,1,both,Mid-range product,Busiest days,Fewest orders,28
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,prior,14,1,14,7.0,10,1,both,Mid-range product,Busiest days,Most orders,28
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,prior,15,1,14,7.0,3,1,both,Mid-range product,Busiest days,Most orders,28
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,prior,18,0,21,0.0,5,1,both,Mid-range product,Busiest days,Average orders,28
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,prior,19,0,22,7.0,11,1,both,Mid-range product,Busiest days,Average orders,28
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,prior,20,0,22,7.0,11,1,both,Mid-range product,Busiest days,Average orders,28
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,prior,21,0,20,7.0,5,1,both,Mid-range product,Busiest days,Average orders,28
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,prior,22,0,22,7.0,15,1,both,Mid-range product,Busiest days,Average orders,28
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,prior,24,4,22,3.0,4,1,both,Mid-range product,Slowest days,Average orders,28
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,prior,25,6,19,16.0,6,1,both,Mid-range product,Regularly busy,Average orders,28
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,prior,27,1,1,5.0,1,1,both,Mid-range product,Busiest days,Fewest orders,28
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,prior,28,0,21,6.0,1,1,both,Mid-range product,Busiest days,Average orders,28
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,prior,1,2,12,NaN,2,0,both,Mid-range product,Regularly busy,Most orders,4
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,prior,2,2,10,21.0,2,1,both,Mid-range product,Regularly busy,Most orders,4
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,prior,3,4,17,2.0,3,1,both,Mid-range product,Slowest days,Average orders,4
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,prior,1,1,9,NaN,1,0,both,Mid-range product,Busiest days,Most orders,10
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,prior,4,0,13,18.0,6,1,both,Mid-range product,Busiest days,Most orders,10
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,prior,6,1,9,8.0,3,1,both,Mid-range product,Busiest days,Most orders,10
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,prior,8,0,17,30.0,10,1,both,Mid-range product,Busiest days,Average orders,10
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,prior,9,4,15,25.0,1,1,both,Mid-range product,Slowest days,Most orders,10
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,prior,1,0,14,NaN,12,0,both,Mid-range product,Busiest days,Most orders,10
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,prior,7,1,16,9.0,10,0,both,Mid-range product,Busiest days,Most orders,23
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,prior,24,1,8,10.0,5,0,both,Mid-range product,Busiest days,Average orders,25
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,prior,5,3,10,7.0,11,0,both,Mid-range product,Slowest days,Most orders,13
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,prior,1,2,20,NaN,8,0,both,Mid-range product,Regularly busy,Average orders,5
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,prior,4,2,10,30.0,7,0,both,Mid-range product,Regularly busy,Most orders,6
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,prior,1,1,14,NaN,2,0,both,Mid-range product,Busiest days,Most orders,3
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,prior,2,1,10,7.0,8,0,both,Mid-range product,Busiest days,Most orders,42
50,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,prior,3,1,10,7.0,2,1,both,Mid-range product,Busiest days,Most orders,42
51,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,prior,5,3,13,7.0,6,1,both,Mid-range product,Slowest days,Most orders,42
52,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,prior,9,2,11,5.0,3,1,both,Mid-range product,Regularly busy,Most orders,42
53,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,prior,12,1,11,4.0,2,1,both,Mid-range product,Busiest days,Most orders,42
54,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,prior,11,2,7,8.0,1,0,both,Mid-range product,Regularly busy,Average orders,40
55,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,prior,2,0,8,30.0,2,0,both,Mid-range product,Busiest days,Average orders,9
56,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,prior,1,1,16,NaN,9,0,both,Mid-range product,Busiest days,Most orders,4
57,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,prior,3,5,16,29.0,1,0,both,Mid-range product,Regularly busy,Most orders,4
58,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,prior,6,0,13,12.0,7,0,both,Mid-range product,Busiest days,Most orders,14
59,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,prior,1,4,15,NaN,11,0,both,Mid-range product,Slowest days,Most orders,6
60,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,prior,5,2,23,4.0,6,0,both,Mid-range product,Regularly busy,Fewest orders,8
61,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,prior,3,3,15,5.0,5,0,both,Mid-range product,Slowest days,Most orders,21
62,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,prior,4,1,17,5.0,6,1,both,Mid-range product,Busiest days,Average orders,21
63,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,prior,20,1,8,13.0,3,1,both,Mid-range product,Busiest days,Average orders,21
64,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,prior,9,2,15,10.0,2,0,both,Mid-range product,Regularly busy,Most orders,31
65,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,prior,13,0,23,6.0,1,1,both,Mid-range product,Busiest days,Fewest orders,31
66,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,prior,14,2,23,9.0,1,1,both,Mid-range product,Regularly busy,Fewest orders,31
67,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,prior,24,2,13,6.0,2,1,both,Mid-range product,Regularly busy,Most orders,31
68,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,prior,30,3,16,8.0,2,1,both,Mid-range product,Slowest days,Most orders,31
69,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,prior,34,4,13,1.0,13,0,both,Mid-range product,Slowest days,Most orders,99
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,prior,4,3,10,7.0,2,0,both,Mid-range product,Slowest days,Most orders,36
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,prior,8,4,11,21.0,2,0,both,Mid-range product,Slowest days,Most orders,9
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,prior,2,0,12,30.0,2,0,both,Mid-range product,Busiest days,Most orders,5
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,prior,3,3,13,30.0,1,1,both,Mid-range product,Slowest days,Most orders,5
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,prior,1,0,17,NaN,11,0,both,Mid-range product,Busiest days,Average orders,5
75,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,prior,2,0,17,30.0,3,0,both,Mid-range product,Busiest days,Average orders,23
76,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,prior,4,4,18,8.0,2,1,both,Mid-range product,Slowest days,Average orders,23
77,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,prior,5,4,15,7.0,1,1,both,Mid-range product,Slowest days,Most orders,23
78,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,prior,6,4,21,14.0,2,1,both,Mid-range product,Slowest days,Average orders,23
79,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,prior,7,4,18,28.0,1,1,both,Mid-range product,Slowest days,Average orders,23
80,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,prior,10,4,7,16.0,4,1,both,Mid-range product,Slowest days,Average orders,23
81,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,prior,14,4,22,1.0,1,1,both,Mid-range product,Slowest days,Average orders,23
82,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,prior,15,4,16,14.0,1,1,both,Mid-range product,Slowest days,Most orders,23
83,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,prior,16,4,15,7.0,2,1,both,Mid-range product,Slowest days,Most orders,23
84,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,prior,20,4,13,8.0,1,1,both,Mid-range product,Slowest days,Most orders,23
85,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,prior,22,4,14,16.0,7,1,both,Mid-range product,Slowest days,Most orders,23
86,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,prior,17,4,18,8.0,16,0,both,Mid-range product,Slowest days,Average orders,23
87,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,prior,6,4,18,14.0,5,0,both,Mid-range product,Slowest days,Average orders,11
88,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,prior,1,0,16,NaN,2,0,both,Mid-range product,Busiest days,Most orders,5
89,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,prior,22,1,16,8.0,8,0,both,Mid-range product,Busiest days,Most orders,22
90,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,prior,4,2,14,14.0,15,0,both,Mid-range product,Regularly busy,Most orders,21
91,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,prior,8,2,14,14.0,9,1,both,Mid-range product,Regularly busy,Most orders,21
92,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,prior,10,0,21,10.0,1,0,both,Mid-range product,Busiest days,Average orders,36
93,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,prior,11,0,19,14.0,4,1,both,Mid-range product,Busiest days,Average orders,36
94,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,prior,16,2,16,4.0,2,1,both,Mid-range product,Regularly busy,Most orders,36
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,prior,8,3,11,23.0,5,0,both,Mid-range product,Slowest days,Most orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,prior,18,1,14,30.0,1,0,both,Mid-range product,Busiest days,Most orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,prior,13,5,16,2.0,8,0,both,Mid-range product,Regularly busy,Most orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,prior,16,3,13,0.0,2,0,both,Mid-range product,Slowest days,Most orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,prior,10,2,15,3.0,6,0,both,Mid-range product,Regularly busy,Most orders,21

# Deriving Columns with loc()

In [47]:
# Flag customers with criteria as 'loyal'
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [51]:
df_ords_prods_merge.loc[(df_ords_prods_merge['max_order'] <= 40) & (df_ords_prods_merge['max_order'] >10), 'loyalty_flag'] = 'Regular customer'

In [53]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [55]:
# Use value_counts()
df_ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15891077
Loyal customer      10293737
New customer         6249398
Name: count, dtype: int64

In [57]:
# Check
df_ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494  Regular customer             6
15     1494  Regular customer             7
16     1494  Regular customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6
20     1540  Regular customer             7
21     1540  Regular customer             8
22     1540  Regular customer             9
23     1540  Regular customer            14
24     1540  Regular customer            15
25     1540  Regular customer            18
26     1540  Regular customer            19
27     1540  Regular customer            20
28     1540  Regular customer            21
29     1540  Regular customer            22
30     1540  Regular customer            24
31     1540  Regular customer            25
32     1540  Regular customer            27
33     1540  Regular customer            28
34     1598      New customer             1
35     1598      New customer             2
36     1598      New customer             3
37     1647      New customer             1
38     1647      New customer             4
39     1647      New customer             6
40     1647      New customer             8
41     1647      New customer             9
42     2833      New customer             1
43     2850  Regular customer             7
44     2857  Regular customer            24
45     3010  Regular customer             5
46     3029      New customer             1
47     3395      New customer             4
48     3904      New customer             1
49     4006    Loyal customer             2
50     4006    Loyal customer             3
51     4006    Loyal customer             5
52     4006    Loyal customer             9
53     4006    Loyal customer            12
54     4122  Regular customer            11
55     4141      New customer             2
56     4343      New customer             1
57     4553      New customer             3
58     4845  Regular customer             6
59     6866      New customer             1

In [59]:
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_combined_merged_updated.pkl'))

# Task

In [62]:
# Check dataframe
df_ords_prods_merge.shape

(32434212, 20)

# Aggregate entire dataframe

In [72]:
df_ords_prods_merge.groupby('department_id').agg({'order_number' : ['mean']})

              order_number
                      mean
department_id
1                15.457687
2                17.277920
3                17.179756
4                17.811403
5                15.213779
6                16.439806
7                17.225773
8                15.340520
9                15.895474
10               20.197148
11               16.170828
12               15.887622
13               16.583304
14               16.757377
15               16.165037
16               17.663250
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

# Analyze the result

In [ ]:
# Instead of just the subset, we're getting the results for the entire data frame.
# The mean for each row changes and varies throughout.

# Create a loyalty flag for existing customers using the transform() and loc() functions

In [75]:
# Check output
df_ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Most orders,32,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Average orders,32,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,21,6.0,20,0,both,Mid-range product,Busiest days,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,13,NaN,10,0,both,Mid-range product,Slowest days,Most orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,17,9.0,11,1,both,Mid-range product,Slowest days,Average orders,3,New customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,7,26.0,7,0,both,Mid-range product,Busiest days,Average orders,26,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Most orders,9,New customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,10,30.0,1,0,both,Mid-range product,Slowest days,Most orders,12,Regular customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,20,19.0,1,0,both,Mid-range product,Busiest days,Average orders,20,Regular customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,12,15.0,2,1,both,Mid-range product,Busiest days,Most orders,20,Regular customer
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,prior,1,5,11,NaN,1,0,both,Mid-range product,Regularly busy,Most orders,10,New customer
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,13,7.0,1,0,both,Mid-range product,Slowest days,Most orders,43,Loyal customer
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,13,7.0,3,1,both,Mid-range product,Slowest days,Most orders,43,Loyal customer
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,12,12.0,4,1,both,Mid-range product,Regularly busy,Most orders,43,Loyal customer
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,10,2.0,8,0,both,Mid-range product,Slowest days,Most orders,13,Regular customer

In [81]:
# Loyalty flag was already done in 4.8 exercise, see above as there is a column for loyalty flag
# Check
df_ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15891077
Loyal customer      10293737
New customer         6249398
Name: count, dtype: int64

# Use loyalty flag and check the basic statistic of the product prices for each loyalty category.

In [84]:
df_ords_prods_merge.groupby('loyalty_flag').agg({'prices' : ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.388747  1.0  99999.0
New customer      13.294370  1.0  99999.0
Regular customer  12.496203  1.0  99999.0

In [86]:
# When looking at the mean, new customers spend the most on average. Loyal customers spend the least and regular customers are somewhere in between.
# Minimum spending for all customers are at $1.00, most likely due to the smallest sku cost is $1.00
# Max prices for all customers are capped out at $99,999.00.

# Create a flag for low spender and high spender

In [93]:
# Create column for average spender in order to find lower and higher spending data
df_ords_prods_merge['average_spending'] = df_ords_prods_merge.groupby(['user_id'])['prices'].transform('mean')

In [91]:
# Check 
df_ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,...,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_spend
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,...,3.0,5,0,both,Mid-range product,Regularly busy,Most orders,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,...,20.0,1,1,both,Mid-range product,Regularly busy,Average orders,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,...,6.0,20,0,both,Mid-range product,Busiest days,Average orders,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,...,NaN,10,0,both,Mid-range product,Slowest days,Most orders,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,...,9.0,11,1,both,Mid-range product,Slowest days,Average orders,3,New customer,4.972414
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,...,26.0,7,0,both,Mid-range product,Busiest days,Average orders,26,Regular customer,6.935398
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,...,30.0,2,0,both,Mid-range product,Regularly busy,Most orders,9,New customer,5.957576
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,...,30.0,1,0,both,Mid-range product,Slowest days,Most orders,12,Regular customer,6.680000
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,...,19.0,1,0,both,Mid-range product,Busiest days,Average orders,20,Regular customer,7.162500
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,...,15.0,2,1,both,Mid-range product,Busiest days,Most orders,20,Regular customer,7.162500
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,prior,1,5,...,NaN,1,0,both,Mid-range product,Regularly busy,Most orders,10,New customer,5.813636
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,...,7.0,1,0,both,Mid-range product,Slowest days,Most orders,43,Loyal customer,5.139394
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,...,7.0,3,1,both,Mid-range product,Slowest days,Most orders,43,Loyal customer,5.139394
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,...,12.0,4,1,both,Mid-range product,Regularly busy,Most orders,43,Loyal customer,5.139394
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,...,2.0,8,0,both,Mid-range product,Slowest days,Most orders,13,Regular customer,6.803797

In [99]:
# Check columns that need focus for easier comprehension
df_ords_prods_merge[['user_id', 'average_spending']].head(15)

    user_id  average_spending
0       138          6.935811
1       138          6.935811
2       709          7.930208
3       764          4.972414
4       764          4.972414
5       777          6.935398
6       825          5.957576
7       910          6.680000
8      1052          7.162500
9      1052          7.162500
10     1379          5.813636
11     1480          5.139394
12     1480          5.139394
13     1480          5.139394
14     1494          6.803797

In [103]:
# Create flags for lower and higher spending
df_ords_prods_merge.loc[df_ords_prods_merge['average_spending'] >= 10, 'spending_flag'] = 'High spender'
df_ords_prods_merge.loc[df_ords_prods_merge['average_spending'] < 10, 'spending_flag'] = 'Low spender'

In [105]:
# Use value_counts()
df_ords_prods_merge['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     31798751
High spender      635461
Name: count, dtype: int64

In [107]:
# Check
df_ords_prods_merge[['user_id', 'average_spending', 'spending_flag']].head(15)

    user_id  average_spending spending_flag
0       138          6.935811   Low spender
1       138          6.935811   Low spender
2       709          7.930208   Low spender
3       764          4.972414   Low spender
4       764          4.972414   Low spender
5       777          6.935398   Low spender
6       825          5.957576   Low spender
7       910          6.680000   Low spender
8      1052          7.162500   Low spender
9      1052          7.162500   Low spender
10     1379          5.813636   Low spender
11     1480          5.139394   Low spender
12     1480          5.139394   Low spender
13     1480          5.139394   Low spender
14     1494          6.803797   Low spender

# Create an order frequency flag that marks the regularity of a user's ordering behavior according to the median.

In [114]:
# Create column for order frequency flags 
df_ords_prods_merge['order_frequency'] = df_ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform('median')

In [116]:
# Check
df_ords_prods_merge.head(20)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,orders_day_of_week,...,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_spend,average_spending,spending_flag,order_frequency
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,prior,28,6,...,both,Mid-range product,Regularly busy,Most orders,32,Regular customer,6.935811,6.935811,Low spender,8.0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,prior,30,6,...,both,Mid-range product,Regularly busy,Average orders,32,Regular customer,6.935811,6.935811,Low spender,8.0
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,prior,2,0,...,both,Mid-range product,Busiest days,Average orders,5,New customer,7.930208,7.930208,Low spender,8.0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,prior,1,3,...,both,Mid-range product,Slowest days,Most orders,3,New customer,4.972414,4.972414,Low spender,9.0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,prior,3,4,...,both,Mid-range product,Slowest days,Average orders,3,New customer,4.972414,4.972414,Low spender,9.0
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,...,both,Mid-range product,Busiest days,Average orders,26,Regular customer,6.935398,6.935398,Low spender,11.0
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,prior,3,2,...,both,Mid-range product,Regularly busy,Most orders,9,New customer,5.957576,5.957576,Low spender,20.0
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,prior,12,3,...,both,Mid-range product,Slowest days,Most orders,12,Regular customer,6.680000,6.680000,Low spender,6.0
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,prior,10,1,...,both,Mid-range product,Busiest days,Average orders,20,Regular customer,7.162500,7.162500,Low spender,10.0
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,prior,15,1,...,both,Mid-range product,Busiest days,Most orders,20,Regular customer,7.162500,7.162500,Low spender,10.0
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,prior,1,5,...,both,Mid-range product,Regularly busy,Most orders,10,New customer,5.813636,5.813636,Low spender,20.0
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,prior,36,3,...,both,Mid-range product,Slowest days,Most orders,43,Loyal customer,5.139394,5.139394,Low spender,7.0
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,prior,38,4,...,both,Mid-range product,Slowest days,Most orders,43,Loyal customer,5.139394,5.139394,Low spender,7.0
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,prior,39,2,...,both,Mid-range product,Regularly busy,Most orders,43,Loyal customer,5.139394,5.139394,Low spender,7.0
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,prior,6,3,...,both,Mid-range product,Slowest days,Most orders,13,Regular customer,6.803797,6.803797,Low spender,7.0
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,prior,7,2,...,both,Mid-range product,Regularly busy,Average orders,13,Regular customer,6.803797,6.803797,Low spender,7.0
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,prior,9,5,...,both,Mid-range product,Regularly busy,Average orders,13,Regular customer,6.803797,6.803797,Low spender,7.0
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,prior,4,2,...,both,Mid-range product,Regularly busy,Fewest orders,28,Regular customer,6.607122,6.607122,Low spender,7.0
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,prior,5,1,...,both,Mid-range product,Busiest days,Average orders,28,Regular customer,6.607122,6.607122,Low spender,7.0
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,prior,6,1,...,both,Mid-range product,Busiest days,Fewest orders,28,Regular customer,6.607122,6.607122,Low spender,7.0

In [120]:
#Check with columns we need to focus on
df_ords_prods_merge[['user_id', 'days_since_prior_order', 'order_frequency']].head(15)

    user_id  days_since_prior_order  order_frequency
0       138                     3.0              8.0
1       138                    20.0              8.0
2       709                     6.0              8.0
3       764                     NaN              9.0
4       764                     9.0              9.0
5       777                    26.0             11.0
6       825                    30.0             20.0
7       910                    30.0              6.0
8      1052                    19.0             10.0
9      1052                    15.0             10.0
10     1379                     NaN             20.0
11     1480                     7.0              7.0
12     1480                     7.0              7.0
13     1480                    12.0              7.0
14     1494                     2.0              7.0

In [124]:
# Create flags for order frequency 
df_ords_prods_merge.loc[df_ords_prods_merge['order_frequency'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'
df_ords_prods_merge.loc[(df_ords_prods_merge['order_frequency'] <= 20) & (df_ords_prods_merge['order_frequency'] > 10), 'order_frequency_flag'] = 'Regular customer'
df_ords_prods_merge.loc[df_ords_prods_merge['order_frequency'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [126]:
# Use value_counts()
df_ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

order_frequency_flag
Frequent customer        21577409
Regular customer          7217134
Non-frequent customer     3639669
Name: count, dtype: int64

In [128]:
# Check
df_ords_prods_merge[['user_id', 'days_since_prior_order', 'order_frequency', 'order_frequency_flag']].head(15)

    user_id  days_since_prior_order  order_frequency order_frequency_flag
0       138                     3.0              8.0    Frequent customer
1       138                    20.0              8.0    Frequent customer
2       709                     6.0              8.0    Frequent customer
3       764                     NaN              9.0    Frequent customer
4       764                     9.0              9.0    Frequent customer
5       777                    26.0             11.0     Regular customer
6       825                    30.0             20.0     Regular customer
7       910                    30.0              6.0    Frequent customer
8      1052                    19.0             10.0    Frequent customer
9      1052                    15.0             10.0    Frequent customer
10     1379                     NaN             20.0     Regular customer
11     1480                     7.0              7.0    Frequent customer
12     1480                     7.0              7.0    Frequent customer
13     1480                    12.0              7.0    Frequent customer
14     1494                     2.0              7.0    Frequent customer

In [130]:
# Export
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_update_1.pkl'))